# -*- coding: utf-8 -*-
"""323_DS6_Lambda_MongoDB_JM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qrKY5mPUA9uJSUC3tOODHDTQpZbEUDQb

# MongoDB with PyMongo

LSDS Unit 3 Sprint 2 Module 3

Some resources:

https://docs.atlas.mongodb.com/getting-started/

https://api.mongodb.com/python/current/

HN Discussion on MongoDB versus PostgreSQL/SQLite: https://news.ycombinator.com/item?id=19158854

## Mongo vs PostgreSQL

Working in Mongo was much different. PostgreSQL seems to make more sense to me with its logic and flow and being a relational database compared to nonrelational such as Mongo.
"""

#Pull out the IP address for this collab notebook
!curl ipecho.net/plain

"""username: admin


password: Q3rOTNfE5I5SlqHu
"""

#How do we figure out our python version?
import sys
print(sys.version)

!pip install pymongo

import pymongo

#Use 3.4 connection string for clarity

client = pymongo.MongoClient("mongodb://jjmorr13:Captainmorgan17@cluster0-shard-00-00-duwdu.mongodb.net:27017,cluster0-shard-00-01-duwdu.mongodb.net:27017,cluster0-shard-00-02-duwdu.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.test

db

#check how many machines
client.nodes

help(db)

dir(db.test)

help(db.test.insert_one)

#Count how many documents
db.test.count_documents({'x':1})

#Insert a document
db.test.insert_one({'x': 1})

#Count again how many documents
db.test.count_documents({'x':1})

#Insert a document again
db.test.insert_one({'x': 1})

#Count again how many documents
db.test.count_documents({'x':1})

db.test.find_one({'x': 1})

db.test.find({'x':1})

curs = db.test.find({'x':1})

list(curs)

jason_doc = {
    'favorite animal': ['Shark', 'Cats']
}

matthew_doc = {
    'favorite animal': 'Platypus'
}

nick_doc = {
    'favorite animal' : 'Hippogriff'
}

db.test.insert_many([jason_doc, matthew_doc, nick_doc])

list(db.test.find())

#Now let's make more docs.

more_docs = []
for i in range(10):
  doc = {'even': i % 2 == 0}
  doc['value'] = i
  more_docs.append(doc)

more_docs

db.test.insert_many(more_docs)

list(db.test.find({'even':False}))

list(db.test.find({'favorite animal': 'Platypus'}))

db.test.update_one({'value':3},
                   {'$inc': {'value': 5}})

"""CRUD - Create Read Update Delete"""

list(db.test.find())

db.test.update_many({'even': True},
                    {'$inc': {'value':100}})

list(db.test.find({'even':True}))

db.test.delete_many({'even':False})

list(db.test.find())

rpg_character = (1, "King Bob", 10, 3, 0, 0, 0)

db.test.insert_one({'rpg_character' : rpg_character})

db.test.insert_one({
    'sql_id': rpg_character[0],
    'name': rpg_character[1],
    'hp': rpg_character[2],
    'level': rpg_character[3]

})

list(db.test.find())





